### ISSUE TITLE
Toyota Down?

### ISSUE THREAD

**Issue by skiblawi** [widewing/ha-toyota-na#99] opened 2024-12-12 10:27 UTC
As of about 6 hours ago, both my HA Toyota NA and my personal version of the base Toyota NA python project are not working. Looks like oneapi.telematicsct.com is no longer found. 

Anyone else experiencing the same?

**Comment by NT1970** [comment] 2024-12-12 11:35
Same. I even tried deleted the entry and re enabling it.

**Comment by seang96** [comment] 2024-12-12 12:27
Looks like it might be a server side change. Car app itself works. I see error on the integration page

`oneapi.telematicsct.com:443 ssl:default [Domain name not found] `

**Comment by winpplui** [comment] 2024-12-12 13:57
Same boat, HA down, Toyota app up

**Comment by gitsbydill** [comment] 2024-12-12 14:00
![image](https://github.com/user-attachments/assets/2da0df42-c959-45b6-bd12-282394dc9837)
for what its worth - pihole shows this domain when my phone uses the toyota app

**Comment by seang96** [comment] 2024-12-12 14:01
In the library the URL is oneapi.telematicsct.com which doesn't have a DNS record anymore. Someone would need to analyze the apps to see what they are pointing to now.

**Comment by seang96** [comment] 2024-12-12 14:03
I tested onecdn and that doesn't work, unless if the API has changed as well.

**Comment by gitsbydill** [comment] 2024-12-12 14:06
the toyota app on ios was updated on Dec 5th - maybe they changed the API/domain then? slowly rolling out?

**Comment by seang96** [comment] 2024-12-12 15:24
I created a PR that should fix it. I did this all on mobile copied my changes to github from mobile too so the formatting and stuff probably sucks. New URL is "https://oneapi-east.telematicsct.com/" and it looks like everything is working after updating it.

**Comment by PenitentTangent2401** [comment] 2024-12-12 15:42
I can confirm that oneapi-east is a valid endpoint. It does look like oneapi-west is also a valid endpoint, but I have not tested to see if it functions the same as the east URL.

My guess is that they moved to regional servers to improve performance. There is likely a mechanism for the CDN to point the app to the closest datacenter.

**Comment by widewing** [comment] 2024-12-12 19:23
Thanks @seang96 , I have merged the PR and pull a new release.

**Closed by widewing** 2024-12-12 19:23 UTC

**Comment by bmitchell76** [comment] 2024-12-12 19:35
I updated to 2.5.0, all my entities showed as unavailable.  I removed the integration, re-added it, and signed in, now I have no entities.

**Comment by bmitchell76** [comment] 2024-12-12 20:22
I removed from HA, and HACS, and reinstalled them, but still no entities.

**Comment by bmitchell76** [comment] 2024-12-12 20:35
I even added a reboot after removing from HACS, I can see my vehicles from the attached JSON downloaded diagnostics, but still no entities.

[config_entry-toyota_na-01JEY906JWKXEJRQ3RJEWZK1N5.json](https://github.com/user-attachments/files/18117195/config_entry-toyota_na-01JEY906JWKXEJRQ3RJEWZK1N5.json)

**Comment by seang96** [comment] 2024-12-12 23:09
> I even added a reboot after removing from HACS, I can see my vehicles from the attached JSON downloaded diagnostics, but still no entities.
> 
> [config_entry-toyota_na-01JEY906JWKXEJRQ3RJEWZK1N5.json](https://github.com/user-attachments/files/18117195/config_entry-toyota_na-01JEY906JWKXEJRQ3RJEWZK1N5.json)
> 

This looks like a different issue. Looking at your json file I see

`remoteSubscriptionStatus": "UNKNOWN",`

This needs to be true for entities to show. You may need to open the app and activate remote services again or refresh status in there may help? In any case it looks unrelated to this issue.

**Comment by bmitchell76** [comment] 2024-12-12 23:16
> > I even added a reboot after removing from HACS, I can see my vehicles from the attached JSON downloaded diagnostics, but still no entities.
> > 
> > [config_entry-toyota_na-01JEY906JWKXEJRQ3RJEWZK1N5.json](https://github.com/user-attachments/files/18117195/config_entry-toyota_na-01JEY906JWKXEJRQ3RJEWZK1N5.json)
> > 
> 
> This looks like a different issue. Looking at your json file I see
> 
> `remoteSubscriptionStatus": "UNKNOWN",`
> 
> This needs to be true for entities to show. You may need to open the app and activate remote services again or refresh status in there may help? In any case it looks unrelated to this issue.

I've tried refreshing from the Toyota app with the same results.

The same JSON has subscription expiration dates in the future.

**Comment by davidr521** [comment] 2024-12-13 00:10
Has a new HACS update been put out? I don’t see anything and I get the same error when reloading   
  
  
  
  
  
  
  

  
  
>

**Comment by davidr521** [comment] 2024-12-13 00:10
Has a new HACS update been put out? I don’t see anything and I get the same error when reloading   
  
  
  
  
  
  
  

  
  
>

**Comment by NT1970** [comment] 2024-12-13 00:26
Just updated, all good now.

**Comment by davidr521** [comment] 2024-12-13 00:29
> Just updated, all good now.

How did you update?

**Comment by NT1970** [comment] 2024-12-13 00:35
In HACS, go to Toyota and re download it. The restart HASS
